# Geo and topography

```{r setup}
#| echo: false
#| warning: false
#| message: false
#| results: hide
here::i_am("atlas-mnhnl.Rproj")
source(here::here("Atlas", "code", "0_Initialisation.R"))
source(here::here("Atlas", "code", "11_Geology.R"))
source(here::here("Atlas", "code", "12_SoilsMap.R"))
# source(here::here("Atlas", "code", "13_DSM.R"))
```

### Author {.author}

## Geology 

```{r geology}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 20
#| fig-height: 15

plot_carte_geologique(uniteGeo_lux, failles_lux, df_excel)
```

```{r geology LEGENDE}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 20
#| fig-height: 11

plot_legende_geologique(uniteGeo_lux, df_excel, cex_legende = 1.28)
```

<details>
<summary><strong> Show french legend description table</strong></summary>

```{r geology description fr}
#| echo: false
#| warning: false
#| message: false

tableau_unites[] <- lapply(tableau_unites, function(x) {
  if (is.character(x)) gsub("[\r\n]+", " ", x) else x
})

knitr::kable(tableau_unites)
```

</details>

<details>
<summary><strong> Show german legend description table</strong></summary>

```{r geology description de}
#| echo: false
#| warning: false
#| message: false
knitr::kable(tableau_unites)
```

</details>

English nomenclature was unavailable

::: {.spacer}
:::



## Altitude {.unnumbered} 

<!-- # ```{r altitude} -->
<!-- # #| echo: false -->
<!-- # #| warning: false -->
<!-- # #| message: false -->
<!-- # carte_altitude(DATAPATH) -->
<!-- # ``` -->


## Soil {.unnumbered}

```{r soil}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 20
#| fig-height: 15

plot_carte_sols(DATAPATH)
```

```{r soil LEGENDE}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 20
#| fig-height: 11


plot_legende_sols(DATAPATH)
```



