project:
  type: book
  pre-render: code/pre-render.R

book:
  title: "Atlas of Hoverflies in Luxembourg"
  chapters:
    - index.qmd
    - introduction.qmd
    - biophysical.qmd
    - history.qmd    
    - ecology.qmd
    - methodology.qmd
    - glossary.qmd
    - species.qmd
    - statistics.qmd
    - conservation.qmd
    - references.qmd

format:
  html:
    number-sections: true
    toc: true
    theme: cosmo 


  pdf:
    documentclass: book

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
