# Biophysical environment of Luxembourg

```{r setup}
#| echo: false
#| warning: false
#| message: false
#| results: hide
here::i_am("atlas-mnhnl.Rproj")
source(here::here("Atlas", "code", "0_Initialisation.R"))
source(here::here("Atlas", "code", "Geology.R"))
source(here::here("Atlas", "code", "SoilsMap.R"))
source(here::here("Atlas", "code", "DSM.R"))
```


## Geology {.unnumbered}

```{r geology}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 20
#| fig-height: 11

plot_carte_geologique(uniteGeo, failles)
plot_legende_geologique(uniteGeo, cex_legende = 1.25)
```

<details>
<summary><strong> Show legend description table</strong></summary>

```{r geology description }
#| echo: false
#| warning: false
#| message: false
knitr::kable(tableau_unites)
```

</details>







### Altitude {.unnumbered} 

```{r altitude}
#| echo: false
#| warning: false 
#| message: false 
carte_altitude(DATAPATH) 
``` 


### Soil {.unnumbered}

```{r soil}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 20
#| fig-height: 11

plot_carte_sols(DATAPATH)
plot_legende_sols(DATAPATH)
```




