# General introduction

Biodiversity citizen science, specifically the huge amount of photo-based
contributions to data collection, has greatly accelerated our ability to
document diversity and distribution of many taxa, and has helped to achieve
thousands of research projects [@REF1].

## Luxembourg {.unnumbered}

Luxembourg is the top country for citizen science activity on iNaturalist
after correcting for country size and population [@REF2]. The MNHNL hosts
a national XXX antennae, and pushes the use of citizen science platforms
such as [**Observation.org**](https://observation.org/) and [**Naturalist.LU**](https://www.inaturalist.lu/) The MNHNL is also active in promoting events making heavy use of such platforms to both experienced
naturalists and the public such as Biodiversity Day, and the City Nature
Challenge. Such events have been shown to lead to useful and massive
contributions [@REF3], but it is also the case in Luxembourg where both
observations and identifications are stimulated. For example, several
first national records were made during the City Nature Challenge: XXX.

## Hoverflies in Luxembourg {.unnumbered}

In Luxembourg, biodiversity citizen science has greatly contributed to our effort to document the distribution of hoverflies. Despite being only % of all research-grade observations (georeferenced, dated, photographic proof, community agreement on the identification), and being only XXX% of all records available to us, biodiversity citizen science has led to first national records, that is considering every other possible source. *Spilomyia manicata* (pageXXX ; [**https://www.inaturalist.lu/observations/233984507**](https://www.inaturalist.lu/observations/233984507)) was first observed by Sam Schaack in August 2024 in the south of the country, and identified by himself, Hinatea Ariey, a user named “sirhck”, and Juliette Pfeiffer.

**Figure XXX**


## Completeness and Recognition {.unnumbered}



## Limits and Opportunities {.unnumbered}

